// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmprdkyuodhpvngifzfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcHJka3l1b2RocHZuZ2lmemZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzU3ODUsImV4cCI6MjA2MDA1MTc4NX0.HrHI8gELmoEQWQlsvvUuN_-vGIbZmig2a0-BIxyNHSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);